name: CI

on:
  push:
    branches: ["dev", "master"]
  pull_request:
    branches: ["dev", "master"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SoftServe_TestProject.sln

      - name: Build
        run: dotnet build SoftServe_TestProject.sln --no-restore

      - name: Test
        run: dotnet test tests/SoftServe_TestProject.Tests/SoftServe_TestProject.Tests.csproj